# This is a basic workflow to help you get started with Actions

name: CI
concurrency: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  DOTNET_VERSION: '5.0.401'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 🛒 Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: ⚙️ Setup dotnet 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: ⚙️ Setup GIT versioning
        uses: dotnet/nbgv@v0.4.0
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        id: nbgv
        with:
          setAllVars: true
      
      - run: echo "NBGV_SemVer2 $NBGV_SemVer2"
      
      - name: Restore dependancies
        run: dotnet restore
      
      - name: 🛠️ Building library in release mode
        run: dotnet build --no-restore --configuration Release

      # pack and publish the nuget package
      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Source/Geckonet.Core/Geckonet.Core.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: ${{env.NBGV_SemVer1}}
          TAG_COMMIT: false
